spring:
  application:
    name: adg-rule
  profiles:
    active: prod  #切换至 dev 即可输出调试信息

logging:
  file:
    path: ./logs

application:
  config:
    expected_quantity: 2000000  #预期规则数量
    fault_tolerance: 0.001 #容错率
    warn_limit: 7 #警告阈值, 规则长度小于该值时会输出警告日志
    batch_size: 10000 #写入文件的批次大小

  # 规则源配置，remote为远程规则，local为本地规则，支持多个规则源
  rule:

     # 仅支持 http/https，不限定响应内容格式
    remote:
      - name: AdGuard 基础过滤器
        path: https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_2_Base/filter.txt

      - name: AdGuard 移动广告过滤器
        path: https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_11_Mobile/filter.txt

      - name: AdGuard 防跟踪保护过滤器
        path: https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_3_Spyware/filter.txt

      - name: AdGuard URL跟踪过滤器
        path: https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_17_TrackParam/filter.txt

      - name: AdGuard 恼人广告过滤器
        path: https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_14_Annoyances/filter.txt 

      - name: AdGuard 解除搜索广告和自我推销过滤器
        path: https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_10_Useful/filter.txt

      - name: AdGuard 中文过滤器
        path: https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_224_Chinese/filter.txt 

      - name: AdAway Default Blocklist
        path: https://adaway.org/hosts.txt

      - name: WindowsSpyBlocker
        path: https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt

      - name: 大圣净化
        path: https://raw.githubusercontent.com/jdlingyu/ad-wars/master/hosts

      - name: AWAvenue-Adblock-Rule 
        path: https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/AWAvenue-Ads-Rule.txt
        
      - name: halflife-list
        path: https://raw.githubusercontent.com/sbwml/halflife-list/master/ad-pc.txt 

      - name: 1024_hosts
        path: https://raw.githubusercontent.com/Goooler/1024_hosts/master/hosts 

      - name: AdBlocker Ultimate 
        path: https://filters.adavoid.org/ultimate-ad-filter.txt 

      - name: damengzhu/banad 
        path: https://raw.githubusercontent.com/damengzhu/banad/main/jiekouAD.txt 

      - name: NoAppDownload  
        path: https://raw.githubusercontent.com/Noyllopa/NoAppDownload/master/NoAppDownload.txt 

      - name: CJX's Annoyance List
        path: https://filters.adtidy.org/extension/ublock/filters/220.txt 

      - name: sccheng460 me
        path: https://raw.githubusercontent.com/sccheng460/me/master/rules.txt
        
      - name: YYY Custom Rules
        path: https://raw.githubusercontent.com/MoonWWY/YYYCustomRules/main/YYYCustomRules.txt
        
      - name: xndeye的私有规则
        path: https://ghproxy.net/https://raw.githubusercontent.com/xndeye/adblock_list/main/rule/private.txt

      - name: adblockfilters规则
        path: https://mirror.ghproxy.com/https://raw.githubusercontent.com/217heidai/adblockfilters/main/rules/adblockdns.txt
        
      - name: 自用白名单规则
        path: https://raw.githubusercontent.com/superbigsteam/adguardhomeguiz/main/rule/zhiyongguiz.txt
        
      - name: anti-AD的DNS过滤版
        path: https://anti-ad.net/easylist.txt
        
      - name: Perflyst and Dandelion Sprout's Smart-TV Blocklist
        path: https://adguardteam.github.io/HostlistsRegistry/assets/filter_7.txt

      - name: I don’t care about cookies
        path: https://www.i-dont-care-about-cookies.eu/abp/

      - name: Fanboy's Annoyance List
        path: https://easylist-downloads.adblockplus.org/fanboy-annoyance.txt
      
      - name: 屏蔽国内广告hosts
        path: https://raw.githubusercontent.com/easonjim/blackhosts/master/hosts
        
      - name: 屏蔽国内各大直播网站hosts
        path: https://raw.githubusercontent.com/easonjim/blackhosts/master/CustomHosts

    #本地规则请将文件放置到项目路径rule目录中
    local:
#      - name: 'local rule'
#        path: 'local-rule.txt'
  output:
    file_header: |  #输出文件头, 占位符${name}将被替换为文件名，如all.txt,  ${date} 将被替换为当前日期
      [ADFS Adblock List]
      ! Title: ${name}
      ! Last Modified: ${date}
      ! Rule Homepage: https://github.com/superbigsteam/adguardhomeguiz
      ! Repository template Homepage: https://github.com/fordes123/ad-filters-subscriber
    path: rule   #规则文件输出路径，相对路径默认从 项目目录开始
    files:
      all.txt: #输出文件名
        - DOMAIN  #域名规则，仅完整域名
        - REGEX   #正则规则，包含正则的域名规则，AdGH支持
        - MODIFY  #修饰规则，添加了一些修饰符号的规则，AdG支持
        - HOSTS   #Hosts规则
      dns.txt:
        - DOMAIN
        - REGEX
        - HOSTS
      hosts.txt:
        - HOSTS
      regex.txt:
        - REGEX
      domain.txt:
        - DOMAIN
      modify.txt:
        - MODIFY
